EXPERIMENT: 23
ROOT_PROJECT: /home/ubuntu/code/therapanacea-project
EXPERIMENT_FOLDER: ${ROOT_PROJECT}/experiments
ROOT_EXPERIMENT: ${EXPERIMENT_FOLDER}/experiment_${EXPERIMENT}

INFERENCE:
  BACKBONE: "resnet18"
  PRINT_FREQ: 1000
  PATH_MODEL : ${..ROOT_EXPERIMENT}/saved_models
  PATH_PREDICTIONS: ${..ROOT_EXPERIMENT}/predictions

  BATCH_SIZE : 512
  PREDICTION_THRESHOLD : 0.5

  DATASET:
    IMAGES_DIR : ./data/val_img/
    N_CLASSES: 1
    RANDOM_SEED: 42

    TRANSFORMS:
      INFERENCE:
        frameworks: ["torchvision", "torchvision"]
        classes: ["Resize", "Normalize"]
        classes_params: [
          {"size": 256},
          {"mean": [0.485, 0.456, 0.406],"std": [0.229, 0.224, 0.225] },
        ]




